### ISSUE TITLE
Does not include Category 1, Schedule 10 or Section 49

### ISSUE THREAD

**Issue by softgrow** [planningalerts-scrapers/city_of_adelaide_development_applications#1]
These can be found at https://epathway.adelaidecitycouncil.com/ePathway/ePathwayProd/Web/GeneralEnquiry/EnquirySearch.aspx

**Comment by equivalentideas** [comment]
Thanks @softgrow 👍  That link 404s for me @softgrow unfortunately.

What are Cat 1, etc. DAs ?

**Comment by softgrow** [comment]
Try https://epathway.adelaidecitycouncil.com/ePathway/ePathwayProd/Web/default.aspx then "Development Application Enquiry" then Select by Date, say last 14 days.

Cat 1 etc are planning applications with no notification or appeal rights but you might want to know about them.
